export const PROFESOR_COLUMNS = [
  {field: 'id' ,headerName: 'ID', width: 70},
  {field: 'semester' ,headerName: 'SEMESTRE', width: 170},
  {field: 'campus' ,headerName: 'SEDE', width: 160},
  {field: 'faculty' ,headerName: 'FACULTAD', width: 170},
  {field: 'formation_level' ,headerName: 'NIVEL DE FORMACION', width: 210},
  {field: 'dedication' ,headerName: 'DEDICACION', width: 170},
  {field: 'total' ,headerName: 'TOTAL', width: 100},
]

export const GRADUATES_COLUMNS = [
  {field: 'id' ,headerName: 'ID', width: 70},
  {field: 'faculty' ,headerName: 'FACULTAD', width: 170},
  {field: 'program' ,headerName: 'PROGRAMA', width: 160},
  {field: 'semester' ,headerName: 'SEMESTRE', width: 170},
  {field: 'total' ,headerName: 'TOTAL', width: 100},
]

export const NEW_STUDENTS_COLUMNS = [
  {field: 'id' ,headerName: 'ID', width: 70},
  {field: 'faculty' ,headerName: 'FACULTAD', width: 170},
  {field: 'program' ,headerName: 'PROGRAMA', width: 160},
  {field: 'semester' ,headerName: 'SEMESTRE', width: 130},
  {field: 'enrolled_poblado' ,headerName: 'INSCRITOS POBLADO', width: 210},
  {field: 'admitted_poblado' ,headerName: 'ADMITIDOS POBLADO', width: 210},
  {field: 'newcomers_poblado' ,headerName: 'NUEVOS POBLADO', width: 210},
  {field: 'enrolled_rionegro' ,headerName: 'INSCRITOS RIONEGRO', width: 210},
  {field: 'admitted_rionegro' ,headerName: 'ADMITIDOS RIONEGRO', width: 210},
  {field: 'newcomers_rionegro' ,headerName: 'NUEVOS RIONEGRO', width: 210},
  {field: 'enrolled_apartado' ,headerName: 'INSCRITOS APARTADO', width: 210},
  {field: 'admitted_apartado' ,headerName: 'ADMITIDOS APARTADO', width: 210},
  {field: 'newcomers_apartado' ,headerName: 'NUEVOS APARTADO', width: 210},
  {field: 'dedication' ,headerName: 'DEDICACION', width: 170},
  {field: 'total' ,headerName: 'TOTAL', width: 100},
]

export const ENROLLED_BY_GENDER_COLUMNS = [
  {field: 'id' ,headerName: 'ID', width: 70},
  {field: 'faculty' ,headerName: 'FACULTAD', width: 170},
  {field: 'program' ,headerName: 'PROGRAMA', width: 160},
  {field: 'semester' ,headerName: 'SEMESTRE', width: 130},
  {field: 'male_newcomers_poblado' ,headerName: 'HOMBRES INSCRITOS POBLADO', width: 280},
  {field: 'female_newcomers_poblado' ,headerName: 'MUJERES INSCRITAS POBLADO', width: 280},
  {field: 'male_newcomers_rionegro' ,headerName: 'HOMBRES INSCRITOS RIONEGRO', width: 280},
  {field: 'female_newcomers_rionegro' ,headerName: 'MUJERES INSCRITAS RIONEGRO', width: 280},
  {field: 'male_newcomers_apartado' ,headerName: 'HOMBRES INSCRITOS APARTADO', width: 280},
  {field: 'female_newcomers_apartado' ,headerName: 'MUJERES INSCRITAS APARTADO', width: 280},
  {field: 'male_former_students_poblado' ,headerName: 'HOMBRES ANTIGUOS POBLADO', width: 280},
  {field: 'female_former_students_poblado' ,headerName: 'MUJERES ANTIGUAS POBLADO', width: 280},
  {field: 'male_former_students_rionegro' ,headerName: 'HOMBRES ANTIGUOS RIONEGRO', width: 280},
  {field: 'female_former_students_rionegro' ,headerName: 'MUJERES ANTIGUAS RIONEGRO', width: 280},
  {field: 'male_former_students_apartado' ,headerName: 'HOMBRES ANTIGUOS APARTADO', width: 280},
  {field: 'female_former_students_apartado' ,headerName: 'MUJERES ANTIGUAS APARTADO', width: 280},
  {field: 'male_total_students_poblado' ,headerName: 'TOTAL HOMBRES POBLADO', width: 280},
  {field: 'female_total_students_poblado' ,headerName: 'TOTAL MUJERES POBLADO', width: 280},
  {field: 'male_total_students_rionegro' ,headerName: 'TOTAL HOMBRES RIONEGRO', width: 280},
  {field: 'female_total_students_rionegro' ,headerName: 'TOTAL MUJERES RIONEGRO', width: 280},
  {field: 'male_total_students_apartado' ,headerName: 'TOTAL HOMBRES APARTADO', width: 280},
  {field: 'female_total_students_apartado' ,headerName: 'TOTAL MUJERES APARTADO', width: 280},
  {field: 'total' ,headerName: 'TOTAL', width: 100},
]

export const ENROLLED_COLUMNS = [
  {field: 'id' ,headerName: 'ID', width: 70},
  {field: 'faculty' ,headerName: 'FACULTAD', width: 170},
  {field: 'program' ,headerName: 'PROGRAMA', width: 160},
  {field: 'semester' ,headerName: 'SEMESTRE', width: 130},
  {field: 'newcomers_poblado' ,headerName: 'MATRICULADOS POBLADO', width: 250},
  {field: 'former_students_poblado' ,headerName: 'ANTIGUOS POBLADO', width: 250},
  {field: 'total_poblado' ,headerName: 'TOTAL POBLADO', width: 250},
  {field: 'newcomers_rionegro' ,headerName: 'MATRICULADOS RIONEGRO', width: 250},
  {field: 'former_students_rionegro' ,headerName: 'ANTIGUOS RIONEGRO', width: 250},
  {field: 'total_rionegro' ,headerName: 'TOTAL RIONEGRO', width: 250},
  {field: 'newcomers_apartado' ,headerName: 'MATRICULADOS APARTADO', width: 250},
  {field: 'former_students_apartado' ,headerName: 'ANTIGUOS APARTADO', width: 250},
  {field: 'total_apartado' ,headerName: 'TOTAL APARTADO', width: 250},
  {field: 'grand_total' ,headerName: 'GRAN TOTAL', width: 190},
]

export const DEFECTION_RATE_COLUMNS = [ 
  {field: 'id' ,headerName: 'ID', width: 70},
  {field: 'faculty' ,headerName: 'FACULTAD', width: 170},
  {field: 'program' ,headerName: 'PROGRAMA', width: 160},
  {field: 'semester' ,headerName: 'SEMESTRE', width: 130},
  {field: 'enrolled_poblado' ,headerName: 'MATRICULADOS POBLADO', width: 250},
  {field: 'academic_retirement_poblado' ,headerName: 'RETIROS ACADEMICOS POBLADO', width: 280},
  {field: 'voluntary_retirement_poblado' ,headerName: 'RETIROS VOLUNTARIOS POBLADO', width: 280},
  {field: 'enrolled_rionegro' ,headerName: 'MATRICULADOS RIONEGRO', width: 250},
  {field: 'academic_retirement_rionegro' ,headerName: 'RETIROS ACADEMICOS RIONEGRO', width: 280},
  {field: 'voluntary_retirement_rionegro' ,headerName: 'RETIROS VOLUNTARIOS RIONEGRO', width: 280},
  {field: 'enrolled_apartado' ,headerName: 'MATRICULADOS APARTADO', width: 250},
  {field: 'academic_retirement_apartado' ,headerName: 'RETIROS ACADEMICOS APARTADO', width: 280},
  {field: 'voluntary_retirement_apartado' ,headerName: 'RETIROS VOLUNTARIOS APARTADO', width: 310},
  {field: 'enrolled_total' ,headerName: 'TOTAL MATRICULADOS', width: 250},
  {field: 'academic_retirement_total' ,headerName: 'TOTAL RETIROS ACADEMICOS', width: 280},
  {field: 'voluntary_retirement_total' ,headerName: 'TOTAL RETIROS VOLUNTARIOS', width: 280},
  {field: 'defection_rate' ,headerName: 'TASA DE DESERCION', width: 250},
]
